import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { useRouter } from "next/router";
import { Toaster } from "react-hot-toast";
import styles from "./HomePage.module.css";
import { Navbar } from "@/component/navbar/NavBar";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster position="bottom-center" />
        <Navbar />
        <div className={styles.container}>{children}</div>
      </body>
    </html>
  );
}
